aws_autoscaling_group:
  - tags:
      Name: foo
    id: foo
aws_eip:
aws_elb:
  - id: foo
aws_iam_group:
  - id: foo
aws_iam_instance_profile:
  - id: foo
aws_iam_policy:
  - id: foo
aws_iam_role:
  - id: foo
aws_iam_user:
  - id: foo
aws_instance:
  - tags:
      Name: foo
  - age:
      before: 168h
aws_internet_gateway:
  - tags:
      Name: foo
aws_launch_configuration:
  - id: foo
aws_nat_gateway:
aws_network_acl:
  - tags:
      Name: foo
aws_network_interface:
  - tags:
      Name: foo
aws_route_table:
  - tags:
      Name: foo
aws_security_group:
  - tags:
      Name: foo
aws_subnet:
  - tags:
      Name: foo
aws_vpc:
  - tags:
      Name: foo
aws_vpc_endpoint:
