options:
  dry-run: true
  max-retries: 1
  s3-force-path-style: true
  regions:
    - ap-southeast-2
    - us-west-2

filters:
  aws_firehose:
  aws_instance:
  aws_s3_bucket:
  aws_dynamodb_table:
  aws_elasticsearch_domain:
