options:
  dry-run: true
  max-retries: 1
  s3-force-path-style: true
  regions:
    - ap-southeast-2
    - us-west-2

filters:
  firehose:
  ec2:
  s3_bucket:
  dynamodb_table:
  elasticsearch_domain:
  rds_instance:
